repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: flake8
        args:
          - --max-line-length=88
          - --select=C,E,F,W,B,B950
          - --ignore=E203,E501,W503,W504

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/prettier/prettier
    rev: "2.0.1"
    hooks:
      - id: prettier
        exclude: static/html/*
