repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --select=C,E,F,W,B,B950
          - --ignore=E203,E501,W503,W504

  - repo: https://github.com/ambv/black
    rev: "23.1.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        exclude: static/html/*
